version: 0.2

env:
  shell: bash
  parameter-store:
    CHECKMARX_BASE_URL: "/nleach/checkmarx_base_url"
phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - wget -q https://github.com/checkmarx-ltd/cx-flow/releases/download/1.6.35/cx-flow-1.6.35.jar
      - ls -lR
  build:
    commands:
      - env
      - java --version
      - java -Dspring.profiles.active=9.0 \
        -jar cx-flow-1.6.35.jar \
        --wrong
      
      
    
