version: 0.2

env:
  shell: bash
  parameter-store:
    CHECKMARX_BASE_URL: "/nleach/checkmarx_base_url"
    CHECKMARX_USERNAME: "/nleach/checkmarx_username"
    CHECKMARX_PASSWORD: "/nleach/checkmarx_password"
phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - wget -q https://github.com/checkmarx-ltd/cx-flow/releases/download/1.6.35/cx-flow-1.6.35-java11.jar
  build:
    commands:
      # CxFlow execution with no issue tracker.  If using an issue tracker,
      # more options are needed.
      - |
        java -Dspring.profiles.active=sast \
        -jar cx-flow-1.6.35-java11.jar \
        --app="SimplyVulnerable" \
        --bug-tracker="NONE" \
        --cx-team="/CxServer" \
        --cx-project="Codebuild-SimplyVulnerable" \
        --scan \
        --f="."
        
        
      
      
    
